### ISSUE TITLE
autoconf error message

### ISSUE THREAD

**Issue by ghost** [timschwartz/metabot#1]
$ autoconf 
configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:16: error: possibly undefined macro: AC_DEFINE
configure.ac:51: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:52: error: possibly undefined macro: AM_COND_IF
configure.ac:52: error: possibly undefined macro: AC_CONFIG_FILES

**Comment by timschwartz** [comment]
Do you have automake installed?

**Comment by ghost** [comment]
yes

**Comment by timschwartz** [comment]
Wait, did you do autoconf? It should be autoreconf

**Comment by ghost** [comment]
there we go, I didn't cache that :P  
Thanks
