### ISSUE TITLE
undefined reference problems with lua and openssl libraries

### ISSUE THREAD

**Issue by ghost** [timschwartz/metabot#2]
source@megumi:~/Projects/c++/metabot$ make
make  all-recursive
make[1]: Entering directory '/storage/mirror/home/source/Projects/c++/metabot'
Making all in src
make[2]: Entering directory '/storage/mirror/home/source/Projects/c++/metabot/src'
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/lua5.1  -I../include  -lssl -lcrypto  -llua5.1  -std=c++11 -lpthread -static-libstdc++ -static-libgcc -g -O2 -MT metabot.o -MD -MP -MF .deps/metabot.Tpo -c -o metabot.o metabot.cpp
mv -f .deps/metabot.Tpo .deps/metabot.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/lua5.1  -I../include  -lssl -lcrypto  -llua5.1  -std=c++11 -lpthread -static-libstdc++ -static-libgcc -g -O2 -MT md5.o -MD -MP -MF .deps/md5.Tpo -c -o md5.o md5.cpp
mv -f .deps/md5.Tpo .deps/md5.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/lua5.1  -I../include  -lssl -lcrypto  -llua5.1  -std=c++11 -lpthread -static-libstdc++ -static-libgcc -g -O2 -MT bot.o -MD -MP -MF .deps/bot.Tpo -c -o bot.o bot.cpp
mv -f .deps/bot.Tpo .deps/bot.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/lua5.1  -I../include  -lssl -lcrypto  -llua5.1  -std=c++11 -lpthread -static-libstdc++ -static-libgcc -g -O2 -MT net.o -MD -MP -MF .deps/net.Tpo -c -o net.o net.cpp
net.cpp: In member function ‘void metabot::net::send(std::string)’:
net.cpp:300:66: warning: ignoring return value of ‘ssize_t write(int, const void_, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
         else ::write(this->sock, message.c_str(), message.size());
                                                                  ^
mv -f .deps/net.Tpo .deps/net.Po
g++ -lssl -lcrypto  -llua5.1  -std=c++11 -lpthread -static-libstdc++ -static-libgcc -g -O2   -o metabot metabot.o md5.o bot.o net.o  -ljson-c 
metabot.o: In function `metabot::console::start()':
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:199: undefined reference to`luaL_newstate'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:200: undefined reference to `luaL_openlibs'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:202: undefined reference to`lua_pushcclosure'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:202: undefined reference to `lua_setfield'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:203: undefined reference to`lua_pushcclosure'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:203: undefined reference to `lua_setfield'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:204: undefined reference to`lua_pushcclosure'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:204: undefined reference to `lua_setfield'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:205: undefined reference to`lua_pushcclosure'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:205: undefined reference to `lua_setfield'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:206: undefined reference to`lua_pushcclosure'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:206: undefined reference to `lua_setfield'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:207: undefined reference to`lua_pushcclosure'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:207: undefined reference to `lua_setfield'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:208: undefined reference to`lua_pushcclosure'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:208: undefined reference to `lua_setfield'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:214: undefined reference to`luaL_loadstring'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:217: undefined reference to `lua_tolstring'
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:214: undefined reference to`lua_pcall'
metabot.o: In function `metabot::console::selectbot(lua_State_)':
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:162: undefined reference to `lua_tolstring'
metabot.o: In function`metabot::console::logon(lua_State_)':
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:149: undefined reference to `lua_tolstring'
metabot.o: In function`metabot::console::say(lua_State_)':
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:123: undefined reference to `lua_tolstring'
metabot.o: In function`metabot::console::openbot(lua_State_)':
/storage/mirror/home/source/Projects/c++/metabot/src/metabot.cpp:131: undefined reference to `lua_tolstring'
bot.o: In function`metabot::bot::bot(std::string)':
/usr/include/c++/4.9/thread:136: undefined reference to `pthread_create'
net.o: In function`metabot::init_ssl_lib()':
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:94: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:95: undefined reference to`ERR_load_BIO_strings'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:96: undefined reference to `ERR_load_crypto_strings'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:97: undefined reference to`SSL_load_error_strings'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:99: undefined reference to `SSL_library_init'
net.o: In function`metabot::net::ssl_ctx()':
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:247: undefined reference to `BIO_new_fp'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:249: undefined reference to`SSLv23_client_method'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:251: undefined reference to `SSL_CTX_new'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:257: undefined reference to`SSL_CTX_ctrl'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:258: undefined reference to `SSL_new'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:259: undefined reference to`SSL_set_fd'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:261: undefined reference to `SSL_connect'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:264: undefined reference to`SSL_get_error'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:253: undefined reference to `BIO_printf'
net.o: In function`metabot::net::~net()':
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:168: undefined reference to `SSL_free'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:169: undefined reference to`X509_free'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:170: undefined reference to `SSL_CTX_free'
net.o: In function`metabot::net::net(std::string, int, int, bool)':
/usr/include/c++/4.9/thread:136: undefined reference to `pthread_create'
net.o: In function`metabot::net::net(std::string, int, int, bool)':
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:146: undefined reference to `SSL_get_peer_certificate'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:149: undefined reference to`X509_NAME_new'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:150: undefined reference to `X509_get_subject_name'
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:152: undefined reference to`X509_NAME_print_ex'
net.o: In function `metabot::net::net(std::string, int, int, bool)':
/usr/include/c++/4.9/thread:136: undefined reference to`pthread_create'
net.o: In function `metabot::net::thread_ssl()':
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:196: undefined reference to`SSL_read'
net.o: In function `metabot::net::send(std::string)':
/storage/mirror/home/source/Projects/c++/metabot/src/net.cpp:299: undefined reference to`SSL_write'
/usr/lib/gcc/x86_64-linux-gnu/4.9/libstdc++.a(thread.o): In function `std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>)':
(.text._ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEE+0x85): undefined reference to`pthread_create'
collect2: error: ld returned 1 exit status
Makefile:333: recipe for target 'metabot' failed
make[2]: *_\* [metabot] Error 1
make[2]: Leaving directory '/storage/mirror/home/source/Projects/c++/metabot/src'
Makefile:433: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/storage/mirror/home/source/Projects/c++/metabot'
Makefile:328: recipe for target 'all' failed
make: **\* [all] Error 2
source@megumi:~/Projects/c++/metabot$

**Comment by timschwartz** [comment]
Can you put your config.log on http://pastebin.com/ ?

What happens when you run 

```
pkg-config lua-5.1 --libs
```

and 

```
pkg-config openssl --libs
```

at the command line?

**Comment by ghost** [comment]
"-llua5.1" and "-lssl -lcrypto"

**Comment by timschwartz** [comment]
What linux distribution are you running?

**Comment by ghost** [comment]
ubuntu 15.10

**Comment by timschwartz** [comment]
64 bit desktop?

**Comment by timschwartz** [comment]
a3421e6092bdec5f50b7766dc3248c346c47485c should fix this. 

Can you `git pull` and test it?

**Comment by ghost** [comment]
That worked, thanks :)

**Comment by timschwartz** [comment]
np

**Comment by ghost** [comment]
btw, there are a lot of these messages during compile:
sqlite3_step failed: NOT NULL constraint failed: memberdef.id_file

**Comment by timschwartz** [comment]
I think that's just from Doxygen generating the documentation. Nothing to worry about, I'll figure out how to get rid of it later.

**Comment by ghost** [comment]
meh, no big deal.
Just thought you'd like to know :D
